import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import ServerProviders from "@/app/Providers/ServerProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const metropolis = localFont({
  src: [
    {
      path: './assets/fonts/Metropolis-Bold.otf',
      weight: '100',
      style: 'Bold',
    },
    {
      path: './assets/fonts/Metropolis-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './assets/fonts/Metropolis-MediumItalic.otf',
      weight: '500',
      style: 'italic',
    },
    {
      path: './assets/fonts/Metropolis-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './assets/fonts/Metropolis-RegularItalic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './assets/fonts/Metropolis-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './assets/fonts/Metropolis-LightItalic.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: './assets/fonts/Metropolis-ExtraLight.otf',
      weight: '100',
      style: 'normal',
    },
    {
      path: './assets/fonts/Metropolis-ExtraLightItalic.otf',
      weight: '100',
      style: 'italic',
    },
    {
      path: './assets/fonts/Metropolis-Thin.otf',
      weight: '100',
      style: 'normal',
    },
    {
      path: './assets/fonts/Metropolis-ThinItalic.otf',
      weight: '100',
      style: 'italic',
    },
  ],
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={metropolis.className}>
        <ServerProviders>{children}</ServerProviders>
      </body>
    </html>
  );
}
