import type { Metadata } from "next";
import DashboardNavBar from "./components/DashboardNavBar";
import { DashboardSideBar, DashboardSideBarItem, DashboardSideBarGroup } from "./components/DashboardSideBar";
import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";
import { IconLayoutDashboard, IconTerminal2, IconDatabase, IconInfoHexagon } from "@tabler/icons-react";
import ParticleLogoDark from "../assets/ParticleLogo";
import UbidotsLogo from "../assets/UbidotsLogo";
export const metadata: Metadata = {
  title: "Dashboard",
//   description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const supabase = createClient();
  // const { data, error } = await supabase.auth.getUser();
  // console.log(data.user);
  // if (!data.user || error) {
  //   redirect('/')
  // }
  return (
        <main>
            <div className=" flex flex-row h-[100vh]">
              <DashboardSideBar>
                <DashboardSideBarItem logo={<IconLayoutDashboard size={30} />} link="/dashboard" title="Dashboard" />
                <DashboardSideBarItem logo={<IconTerminal2 size={30} />} link="/cmd" title="Commandline" />
                <DashboardSideBarItem logo={<IconDatabase size={30} />} link="/database" title="Database" />
                <DashboardSideBarItem logo={<IconInfoHexagon size={30} />} link="/About" title="About" />
                <DashboardSideBarGroup className=" p-0" logo={<ParticleLogoDark size={48} />} title="Particle.io" >
                  <DashboardSideBarItem logo={<IconLayoutDashboard size={30} />} link="/dashboard" title="Dashboard" />
                  <DashboardSideBarItem logo={<IconTerminal2 size={30} />} link="/cmd" title="Commandline" />
                  <DashboardSideBarItem logo={<IconDatabase size={30} />} link="/database" title="Database" />
                  <DashboardSideBarItem logo={<IconInfoHexagon size={30} />} link="/About" title="About" />
                </DashboardSideBarGroup>
                <DashboardSideBarGroup logo={<UbidotsLogo size={30} />} title="Ubidots" >
                  <DashboardSideBarItem logo={<IconLayoutDashboard size={30} />} link="/dashboard" title="Dashboard" />
                  <DashboardSideBarItem logo={<IconTerminal2 size={30} />} link="/cmd" title="Commandline" />
                  <DashboardSideBarItem logo={<IconDatabase size={30} />} link="/database" title="Database" />
                  <DashboardSideBarItem logo={<IconInfoHexagon size={30} />} link="/About" title="About" />
                </DashboardSideBarGroup>
              </DashboardSideBar>
              {children}
            </div>
        </main>
  );
}
